### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by llelectronics** [blue-systems/neon-pinebook-remix#13]
We have packaging for the firmware files here: 
https://github.com/netrunner-pine64/rtl8723ds-bt-firmware

The sources (bt-firmware) is hiding here: 
https://github.com/ayufan-pine64/linux-build

**Comment by shadeslayer** [comment]
Bluetooth will only work when that job is run once at boot and only once. Restarting that job will deactivate bluetooth and a hard reset will be needed.

Is there something else blocking this ticket to be closed?

**Comment by adriaandegroot** [comment]
The latest PB image has an on-boot script that switches on BT, This has been confirmed to work on at least three machines (although I can't find my BT mouse to test it with).
