### ISSUE TITLE
package live-config

### ISSUE THREAD

**Issue by jriddell** [blue-systems/neon-pinebook-remix#20]
package live-config for Neon, Debian's live session setup scripts.  Works in user space rather than initrd space which casper uses so easier to use.

**Comment by jriddell** [comment]
Debian's live-config works with user space scripts in /lib/live/config/
To use Ubuntu's casper I'd need to rebuild the initrd which is just something easier to avoid if its not needed since I don't know how that initrd was made in the first place.
Closing as long since done

**Comment by star-buck** [comment]
and closed
