### ISSUE TITLE
Dolphin: add "Up" key in toolbar, also possibly others like "Add new Folder" or "Delete"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/neon-pinebook-remix#28]

**Comment by star-buck** [comment]
@bhush9 : this got "Reset" (like in Netrunner lately), would be nice to have restored again.

**Comment by bhush9** [comment]
Fixed in : https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180620-0516/
