### ISSUE TITLE
Build Tracker (list of img+1)

### ISSUE THREAD

**Issue by jriddell** [blue-systems/neon-pinebook-remix#31]
I'll use this issue report to list new builds

**Comment by bhush9** [comment]
http://weegie.edinburghlinux.co.uk/~neon/images/pinebook-remix/20180209-1549/

- Show battery percentage by default
- Disable hot corners
- Disable suspend session
- Fixes regarding video playback from @davidedmundson

**Comment by star-buck** [comment]
Awesome, dloading now.

**Comment by bhush9** [comment]
http://weegie.edinburghlinux.co.uk/~neon/images/pinebook-remix/20180319-1110/

- Fixes the wireless icons
- Fixes the libreoffice look (libreoffice-gtk3 packaged in)

**Comment by bhush9** [comment]
https://files.kde.org/neon/images/pinebook-remix-nonfree/bionic/20180504-1120/

- Bionic  based image
- Fix for sddm autostart

Errata:

- Sloooooooow on first startup.
